export const VERIFIED_RESTAURANT_CATALOG_DATE = '2026-07-14'

export const verifiedRestaurantCatalog = [
  {
    id: 1,
    name: 'Cơm Tấm Ba Ghiền',
    address: '84 Dang Van Ngu Street, Ward 10, Phu Nhuan District, Ho Chi Minh City',
    district: 'Phu Nhuan',
    category: 'Broken Rice',
    latitude: 10.7942258,
    longitude: 106.6693206,
    avgRating: 0,
    priceRange: '₫',
    featuredDish: 'Charcoal-grilled pork chop with broken rice',
    description:
      'A long-running broken-rice specialist known for a large charcoal-grilled pork chop served with pickled radish and sweet-sour fish sauce.',
    imageUrl: null,
    imageAttribution: null,
    sourceUrl:
      'https://guide.michelin.com/sg/en/ho-chi-minh/ho-chi-minh_2978179/restaurant/com-tam-ba-ghien',
  },
  {
    id: 2,
    name: 'Cục Gạch Quán',
    address: '10 Dang Tat Street, Tan Dinh Ward, District 1, Ho Chi Minh City',
    district: 'District 1',
    category: 'Vietnamese',
    latitude: 10.7929997,
    longitude: 106.6889296,
    avgRating: 0,
    priceRange: '₫₫',
    featuredDish: 'Canh chua cá hú (sour fish soup)',
    description:
      'A Vietnamese restaurant in a restored house serving home-style dishes, including sour fish soup and lemongrass-chilli fried tofu.',
    imageUrl: null,
    imageAttribution: null,
    sourceUrl:
      'https://guide.michelin.com/en/ho-chi-minh/ho-chi-minh_2978179/restaurant/cuc-gach-quan',
  },
  {
    id: 3,
    name: 'Bếp Mẹ Ỉn (Lê Thánh Tôn)',
    address: '136/9 Le Thanh Ton Street, Ben Thanh Ward, District 1, Ho Chi Minh City',
    district: 'District 1',
    category: 'Vietnamese',
    latitude: 10.773828,
    longitude: 106.698061,
    avgRating: 0,
    priceRange: '₫',
    featuredDish: 'Vietnamese pancake with shrimp and pork',
    description:
      'A casual Vietnamese restaurant known for its shrimp-and-pork pancake and fried rice with shrimp and egg served in a coconut shell.',
    imageUrl: null,
    imageAttribution: null,
    sourceUrl:
      'https://guide.michelin.com/us/en/ho-chi-minh/ho-chi-minh_2978179/restaurant/bep-me-in-le-thanh-ton',
  },
  {
    id: 4,
    name: 'Phở Minh',
    address: '63/6 Pasteur Street, Ben Nghe Ward, District 1, Ho Chi Minh City',
    district: 'District 1',
    category: 'Phở',
    latitude: 10.774811,
    longitude: 106.700278,
    avgRating: 0,
    priceRange: '₫',
    featuredDish: 'Traditional beef phở and pâté chaud',
    description:
      'A tucked-away breakfast spot serving traditional beef phở alongside pâté chaud, a warm puff-pastry snack with meat filling.',
    imageUrl: null,
    imageAttribution: null,
    sourceUrl:
      'https://guide.michelin.com/en/ho-chi-minh/ho-chi-minh_2978179/restaurant/pho-minh',
  },
  {
    id: 5,
    name: 'Bún Bò Huế Cô Như',
    address: '274/29 Vo Van Tan Street, Ward 5, District 3, Ho Chi Minh City',
    district: 'District 3',
    category: 'Beef Noodle Soup',
    latitude: 10.7814431,
    longitude: 106.6948107,
    avgRating: 0,
    priceRange: '₫',
    featuredDish: 'Bún bò thập cẩm (mixed beef noodle soup)',
    description:
      'A small noodle shop specializing in Huế-style beef noodle soup, with a mixed bowl that combines several beef cuts and garnishes.',
    imageUrl: null,
    imageAttribution: null,
    sourceUrl:
      'https://guide.michelin.com/us/en/ho-chi-minh/ho-chi-minh_2978179/restaurant/bun-bo-hue-co-nhu',
  },
  {
    id: 6,
    name: 'Xôi Gà Number One',
    address: '15 Nguyen Trung Truc Street, Ben Thanh Ward, District 1, Ho Chi Minh City',
    district: 'District 1',
    category: 'Sticky Rice',
    latitude: 10.7737822,
    longitude: 106.6992243,
    avgRating: 0,
    priceRange: '₫',
    featuredDish: 'Xôi gà (chicken sticky rice)',
    description:
      'A street-food shop serving savoury chicken sticky rice as well as sweet-corn sticky rice with a choice of toppings.',
    imageUrl: null,
    imageAttribution: null,
    sourceUrl:
      'https://guide.michelin.com/vn/en/ho-chi-minh/ho-chi-minh_2978179/restaurant/xoi-ga-number-one',
  },
  {
    id: 7,
    name: 'Ốc Đào (Cầu Ông Lãnh)',
    address: '212B/D48 Nguyen Trai Street, Cau Ong Lanh Ward, District 1, Ho Chi Minh City',
    district: 'District 1',
    category: 'Seafood',
    latitude: 10.7652142,
    longitude: 106.6846551,
    avgRating: 0,
    priceRange: '₫',
    featuredDish: 'Garlic-butter sautéed and salt-grilled shellfish',
    description:
      'A shellfish restaurant offering snails and other seafood prepared in styles such as garlic-butter sautéing and salt grilling.',
    imageUrl: null,
    imageAttribution: null,
    sourceUrl:
      'https://guide.michelin.com/en/ho-chi-minh/ho-chi-minh_2978179/restaurant/oc-%C4%91ao',
  },
  {
    id: 8,
    name: 'Ốc Oanh',
    address: '534 Vinh Khanh Street, Khanh Hoi Ward, District 4, Ho Chi Minh City',
    district: 'District 4',
    category: 'Seafood',
    latitude: 10.7608558,
    longitude: 106.7046422,
    avgRating: 0,
    priceRange: '₫₫',
    featuredDish: 'Whelks, prawns, lobster, octopus and crab',
    description:
      'A busy seafood destination on Vinh Khanh Street with a broad selection that includes whelks, prawns, lobster, octopus and crab.',
    imageUrl: null,
    imageAttribution: null,
    sourceUrl:
      'https://guide.michelin.com/en/ho-chi-minh/ho-chi-minh_2978179/restaurant/oc-oanh',
  },
  {
    id: 9,
    name: 'Phở Việt Nam (Bến Thành)',
    address: '14 Pham Hong Thai Street, Ben Thanh Ward, District 1, Ho Chi Minh City',
    district: 'District 1',
    category: 'Phở',
    latitude: 10.771252,
    longitude: 106.696209,
    avgRating: 0,
    priceRange: '₫',
    featuredDish: 'Phở thố đá (phở served in a hot stone bowl)',
    description:
      'A phở specialist whose signature presentation serves the broth in a heated stone bowl with the noodles, herbs and meat alongside.',
    imageUrl: null,
    imageAttribution: null,
    sourceUrl:
      'https://guide.michelin.com/en/ho-chi-minh/ho-chi-minh_2978179/restaurant/pho-viet-nam-district-1',
  },
  {
    id: 10,
    name: 'Bánh Xèo 46A',
    address: '46A Dinh Cong Trang Street, Tan Dinh Ward, District 1, Ho Chi Minh City',
    district: 'District 1',
    category: 'Vietnamese Pancakes',
    latitude: 10.7896047,
    longitude: 106.6912995,
    avgRating: 0,
    priceRange: '₫',
    featuredDish: 'Bánh xèo (crispy Vietnamese pancake)',
    description:
      'A long-established open-air restaurant specializing in crisp bánh xèo pancakes filled with pork, shrimp and bean sprouts.',
    imageUrl: null,
    imageAttribution: null,
    sourceUrl:
      'https://guide.michelin.com/ph/en/ho-chi-minh/ho-chi-minh_2978179/restaurant/banh-xeo-46a',
  },
].map((restaurant) => ({
  ...restaurant,
  verifiedAt: VERIFIED_RESTAURANT_CATALOG_DATE,
}))
